name: Daily Standup Report

description: |
  This GitHub Actions workflow runs on weekdays at 17:45 Taiwan time (UTC 09:45).
  It clones the private work repository, extracts today's Git commit logs, and calls
  the Dify workflow API to generate a standup report (e.g., posted to Discord).

on:
  schedule:
    - cron: '45 9 * * 1-5'  # Weekdays at 17:45 (Taiwan) => 09:45 UTC
  workflow_dispatch:       # Optional manual trigger

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout work repo
        uses: actions/checkout@v4
        with:
          repository: w101-admin/W101-TalentSearchHub
          token: ${{ secrets.GH_PAT }}

      - name: Get today's date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Get commit messages (today only)
        id: commits
        run: |
          since="$(date +'%Y-%m-%d')T00:00:00Z"
          until="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          logs=$(git log --since="$since" --until="$until" --pretty=format:'- %s')
          echo "LOGS<<EOF" >> $GITHUB_ENV
          echo "$logs" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Call Dify workflow endpoint
        run: |
          curl -X POST 'http://44.243.2.205/v1/workflows/run' \
            --header 'Authorization: Bearer ${{ secrets.WORKFLOW_API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "inputs": {
                "date": "'"${{ env.DATE }}"'",
                "repo": "w101-admin/W101-TalentSearchHub",
                "author": "github-actions",
                "commit_logs": "'"${{ env.LOGS }}"'"
              },
              "response_mode": "streaming",
              "user": "abc-123"
            }'
