name: Daily Standup Report

on:
  schedule:
    - cron: '45 9 * * 1-5'  # 平日台灣 17:45（UTC 09:45）
  workflow_dispatch:        # 可手動觸發

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout work repo (all branches)
        uses: actions/checkout@v4
        with:
          repository: w101-admin/W101-TalentSearchHub
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # 抓取所有分支完整歷史紀錄

      - name: Get today's date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Get commit messages from all branches by YouCheng29
        id: commits
        run: |
          since="$(date +'%Y-%m-%d')T00:00:00Z"
          until="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          logs=$(git log --all --since="$since" --until="$until" --author="YouCheng29" --pretty=format:'- %s')

          if [ -z "$logs" ]; then
            logs="（今天沒有來自 YouCheng29 的 commit）"
          fi

          echo "LOGS<<EOF" >> $GITHUB_ENV
          echo "$logs" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Call Dify Workflow
        run: |
          curl -X POST 'http://44.243.2.205/v1/workflows/run' \
            --header 'Authorization: Bearer ${{ secrets.WORKFLOW_API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "inputs": {
                "date": "'"${{ env.DATE }}"'",
                "repo": "w101-admin/W101-TalentSearchHub",
                "author": "YouCheng29",
                "commit_logs": "'"${{ env.LOGS }}"'"
              },
              "response_mode": "streaming",
              "user": "abc-123"
            }'
